/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas_view;

import Academia.Aluno;
import Academia.Usuario;
import Academia.Metodos;
import Academia.Personal;
import Academia.Relatorios;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author samue
 */
public class Login_tela extends javax.swing.JFrame {

    private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /**
     * Creates new form Login_tela
     */
    public Login_tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email_login = new javax.swing.JTextField();
        senha_login = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(email_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 230, 30));

        senha_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha_loginActionPerformed(evt);
            }
        });
        getContentPane().add(senha_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 220, 30));

        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 220, 70));

        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 693, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/WhatsApp Image 2025-06-07 at 15.52.34.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1254, 862));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void senha_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senha_loginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add y
        Metodos mts = new Metodos();
        try {
            String ver = mts.logar(this.getEmail_login().getText(), this.getSenha_login().getText());

            this.setId(mts.retornoID(this.getEmail_login().getText()));

            if (ver.equals("aluno")) {
                Tela_aluno tla = new Tela_aluno();
                Relatorios rel = new Relatorios();
                Aluno alunoLogado = rel.dados_aluno(this.getId());
                Sessao_usuario.setUsuarioLogado(alunoLogado);
                JOptionPane.showMessageDialog(this, "Bem vindo!");
                tla.setVisible(true);
                this.dispose();

            } else if (ver.equals("personal")) {
                Relatorios rel1 = new Relatorios();               
                 Personal personalLogado = rel1.dados_personal(mts.retornoID(this.email_login.getText()));
                  Sessao_usuario.setUsuarioLogado(personalLogado);
                  JOptionPane.showMessageDialog(this, "Bem vindo!");
                  Tela_personal pers = new Tela_personal();
                  pers.setVisible(true);
                  this.dispose();
               
                
                

            } else if (ver.equals("adm")) {

            } else {
                JOptionPane.showMessageDialog(this, "erro verifique se senha ou email estao corretos!");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login_tela.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Tela_cadastro tlc = new Tela_cadastro();
        tlc.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public JTextField getEmail_login() {
        return email_login;
    }

    public void setEmail_login(JTextField email_login) {
        this.email_login = email_login;
    }

    public JTextField getSenha_login() {
        return senha_login;
    }

    public void setSenha_login(JTextField senha_login) {
        this.senha_login = senha_login;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_login;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField senha_login;
    // End of variables declaration//GEN-END:variables
}
