/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas_view;

import Academia.Alterar;
import Academia.Aluno;
import Academia.Metodos;
import Academia.Personal;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author samue
 */

public class Tela_dados_personal extends javax.swing.JFrame {
     private void carregarDadosPersonal() {
        Personal pers = (Personal) Sessao_usuario.getUsuarioLogado();
        Metodos mts = new Metodos();
        if (pers != null) {
            this.personal_nome.setText(pers.getNome());
            this.personal_email.setText(pers.getEmail());
            this.personal_cpf.setText(pers.getCpf());
            String dataFormatada = mts.converterData(pers.getDataNasc().toString());
            this.personal_data.setText(dataFormatada);
            this.Personal_especialidade.setText(pers.getEspecialidade());
            this.personal_senha.setText(pers.getSenha()); // cuidado com segurança

        } else {
            System.out.println("Nenhum personal está logado.");
        }
    }
    /**
     * Creates new form Tela_dados_personal
     */
    public Tela_dados_personal() {
        initComponents();
        carregarDadosPersonal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personal_senha = new javax.swing.JTextField();
        personal_nome = new javax.swing.JTextField();
        personal_email = new javax.swing.JTextField();
        Personal_especialidade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        personal_data = new javax.swing.JFormattedTextField();
        personal_cpf = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personal_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_senhaActionPerformed(evt);
            }
        });
        getContentPane().add(personal_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 250, 30));

        personal_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(personal_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 240, 30));

        personal_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_emailActionPerformed(evt);
            }
        });
        getContentPane().add(personal_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 260, 30));

        Personal_especialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Personal_especialidadeActionPerformed(evt);
            }
        });
        getContentPane().add(Personal_especialidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 280, 30));

        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 90, 160, 60));

        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 110, 40));

        try {
            personal_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(personal_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 70, 30));

        try {
            personal_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(personal_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 280, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_dados_personal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1056, 665));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void personal_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal_senhaActionPerformed

    private void personal_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal_nomeActionPerformed

    private void personal_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal_emailActionPerformed

    private void Personal_especialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Personal_especialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Personal_especialidadeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    
        Personal personal = (Personal) Sessao_usuario.getUsuarioLogado();
        Metodos metodos = new Metodos();

        // Recupera o ID com base no e-mail antigo (antes de mudar)
        try {
            int id = metodos.retornoID(personal.getEmail()); // usa o e-mail antigo da sessão
            personal.setId(id);
        } catch (SQLException ex) {
            Logger.getLogger(Tela_dados_personal.class.getName()).log(Level.SEVERE, "Erro ao obter ID do personal", ex);
            JOptionPane.showMessageDialog(this, "Erro ao obter ID do personal: " + ex.getMessage());
            return;
        }

        // Atualiza os dados com os campos da tela
        personal.setNome(this.personal_nome.getText());
        personal.setEmail(this.personal_email.getText());
        personal.setCpf(this.personal_cpf.getText());
        personal.setDataNasc(this.personal_data.getText());
        personal.setEspecialidade(this.Personal_especialidade.getText());
        personal.setSenha(this.personal_senha.getText());
        

        Alterar alt = new Alterar();

        try {
            alt.alterarPersonal(personal);
            JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso!");
            Sessao_usuario.setUsuarioLogado(personal); // Atualiza sessão com dados novos
        } catch (SQLException ex) {
            Logger.getLogger(Tela_dados_personal.class.getName()).log(Level.SEVERE, "Erro ao atualizar dados", ex);
            JOptionPane.showMessageDialog(this, "Erro ao alterar os dados: " + ex.getMessage());
        }
    


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
             // TODO add your handling code here:
             Tela_personal tl = new Tela_personal();
             tl.setVisible(true);
             this.dispose();
         } catch (SQLException ex) {
             Logger.getLogger(Tela_dados_personal.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    public JTextField getPersonal_especialidade() {
    return Personal_especialidade;
}

    public void setPersonal_especialidade(JTextField Personal_especialidade) {
    this.Personal_especialidade = Personal_especialidade;
}

    public JFormattedTextField getPersonal_cpf() {
    return personal_cpf;
}

    public void setPersonal_cpf(JFormattedTextField personal_cpf) {
    this.personal_cpf = (JFormattedTextField) personal_cpf;
}

    public JFormattedTextField getPersonal_data() {
    return personal_data;
}

    public void setPersonal_data(JFormattedTextField personal_data) {
    this.personal_data = (JFormattedTextField) personal_data;
}

    public JTextField getPersonal_email() {
    return personal_email;
}

    public void setPersonal_email(JTextField personal_email) {
    this.personal_email = personal_email;
}

    public JTextField getPersonal_nome() {
    return personal_nome;
}

    public void setPersonal_nome(JTextField personal_nome) {
    this.personal_nome = personal_nome;
}

    public JTextField getPersonal_senha() {
    return personal_senha;
}

    public void setPersonal_senha(JTextField personal_senha) {
    this.personal_senha = personal_senha;
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Tela_dados_personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Tela_dados_personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Tela_dados_personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Tela_dados_personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Tela_dados_personal().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Personal_especialidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField personal_cpf;
    private javax.swing.JFormattedTextField personal_data;
    private javax.swing.JTextField personal_email;
    private javax.swing.JTextField personal_nome;
    private javax.swing.JTextField personal_senha;
    // End of variables declaration//GEN-END:variables
}
