/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas_view;

import Academia.Adm;
import Academia.Alterar;
import Academia.Metodos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author samuel e matheus
 */
public class Tela_dadosAdm extends javax.swing.JFrame {
    public void carregar_dados(){
        Adm adm = (Adm) Sessao_usuario.getUsuarioLogado();
        Metodos mts = new Metodos();
        
        adm_nome.setText(adm.getNome());
        adm_cpf.setText(adm.getCpf());        
        adm_email.setText(adm.getEmail());
        String dataFormatada = mts.converterData(adm.getDataNasc().toString());
        adm_data.setText(dataFormatada);
        adm_setor.setText(adm.getSetor());
        adm_telefone.setText(adm.getNumero_comercial());
        adm_desc.setText(adm.getDesc());
        adm_senha.setText(adm.getSenha());// senha ocultada
    }
    /**
     * Creates new form Tela_dadosAdm
     */
    public Tela_dadosAdm() {
        initComponents();
        carregar_dados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adm_telefone = new javax.swing.JTextField();
        adm_desc = new javax.swing.JTextField();
        adm_setor = new javax.swing.JTextField();
        adm_email = new javax.swing.JTextField();
        adm_nome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        adm_senha = new javax.swing.JPasswordField();
        adm_data = new javax.swing.JFormattedTextField();
        adm_cpf = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(adm_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 310, 30));
        getContentPane().add(adm_desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 250, 30));
        getContentPane().add(adm_setor, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 310, 30));
        getContentPane().add(adm_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 250, 30));
        getContentPane().add(adm_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 250, 30));

        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 150, 50));

        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 100, 40));

        adm_senha.setText("jPasswordField1");
        getContentPane().add(adm_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 260, 30));

        try {
            adm_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(adm_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 300, 30));

        try {
            adm_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(adm_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 310, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela_dados_adm.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Adm adm = (Adm) Sessao_usuario.getUsuarioLogado();
        try {
            int id = Metodos.retornoID(adm.getEmail()); // e-mail ainda não alterado
            adm.setId(id);
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Dados_aluno.class.getName()).log(Level.SEVERE, "Erro ao obter ID do aluno", ex);
            JOptionPane.showMessageDialog(this, "Erro ao obter ID do aluno: " + ex.getMessage());
            return; // interrompe se o ID falhar
        }

// Só agora atualiza os dados com base nos campos da tela
        adm.setNome(this.adm_nome.getText());
        adm.setEmail(this.adm_email.getText());
        adm.setCpf(this.adm_cpf.getText());
        adm.setDesc(this.adm_desc.getText());
        adm.setSenha(new String(this.adm_senha.getPassword()));
        adm.setDataNasc(this.adm_data.getText());
        adm.setNumero_comercial(this.adm_telefone.getText());
        adm.setSetor(this.adm_setor.getText());

        Metodos mt = new Metodos();
        Alterar alt = new Alterar();

        try {
            alt.alterarAdm(adm);
            JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso!");
            Sessao_usuario.setUsuarioLogado(adm); // Atualiza sessão com dados novos
            carregar_dados();
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Dados_aluno.class.getName()).log(Level.SEVERE, "Erro ao atualizar dados", ex);
            JOptionPane.showMessageDialog(this, "Erro ao alterar os dados: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Tela_adm tl = new Tela_adm();
        tl.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField adm_cpf;
    private javax.swing.JFormattedTextField adm_data;
    private javax.swing.JTextField adm_desc;
    private javax.swing.JTextField adm_email;
    private javax.swing.JTextField adm_nome;
    private javax.swing.JPasswordField adm_senha;
    private javax.swing.JTextField adm_setor;
    private javax.swing.JTextField adm_telefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
