/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas_view;

import Academia.Alterar;
import Academia.Usuario;
import Academia.Aluno;
import Academia.Metodos;
import Academia.Relatorios;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author samue
 */
public class Tela_Dados_aluno extends javax.swing.JFrame {

    private void carregarDadosAluno() {
        Aluno al = (Aluno) Sessao_usuario.getUsuarioLogado();

        if (al != null) {
            select_nome.setText(al.getNome());
            select_email1.setText(al.getEmail());
            select_cpf.setText(al.getCpf());
            select_datanasc.setText(al.getDataNasc().toString());
            select_objetivo.setText(al.getObjetivo());
            select_senha.setText(al.getSenha()); // cuidado com segurança

        } else {
            System.out.println("Nenhum aluno está logado.");
        }
    }

    /**
     * Creates new form Tela_Dados_aluno
     */
    public Tela_Dados_aluno() {
        initComponents();
        carregarDadosAluno(); // carrega os dados do aluno logado
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        select_datanasc = new javax.swing.JTextField();
        select_nome = new javax.swing.JTextField();
        select_cpf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        select_objetivo = new javax.swing.JTextArea();
        select_senha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        select_email1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(select_datanasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 170, 30));

        select_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(select_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 270, 30));
        getContentPane().add(select_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 270, 30));

        select_objetivo.setColumns(20);
        select_objetivo.setRows(5);
        jScrollPane1.setViewportView(select_objetivo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 250, 30));
        getContentPane().add(select_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 270, 30));

        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 160, 50));

        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, 40));
        getContentPane().add(select_email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 270, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_dados_alimo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void select_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_nomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Aluno aluno = (Aluno) Sessao_usuario.getUsuarioLogado();

// Recupera o ID com base no e-mail antigo (antes de mudar o email)
        try {
            int id = Metodos.retornoID(aluno.getEmail()); // e-mail ainda não alterado
            aluno.setId(id);
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Dados_aluno.class.getName()).log(Level.SEVERE, "Erro ao obter ID do aluno", ex);
            JOptionPane.showMessageDialog(this, "Erro ao obter ID do aluno: " + ex.getMessage());
            return; // interrompe se o ID falhar
        }

// Só agora atualiza os dados com base nos campos da tela
        aluno.setNome(this.select_nome.getText());
        aluno.setEmail(this.select_email1.getText());
        aluno.setCpf(this.select_cpf.getText());
        aluno.setObjetivo(this.select_objetivo.getText());
        aluno.setSenha(new String(this.select_senha.getPassword()));
        aluno.setDataNasc(this.select_datanasc.getText());
        aluno.setStatus("Ativo");

        Metodos mt = new Metodos();
        Alterar alt = new Alterar();

        try {
            alt.alterarAluno(aluno);
            JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso!");
            Sessao_usuario.setUsuarioLogado(aluno); // Atualiza sessão com dados novos
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Dados_aluno.class.getName()).log(Level.SEVERE, "Erro ao atualizar dados", ex);
            JOptionPane.showMessageDialog(this, "Erro ao alterar os dados: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public JTextField getSelect_cpf() {
        return select_cpf;
    }

    public void setSelect_cpf(JTextField select_cpf) {
        this.select_cpf = select_cpf;
    }

    public JTextField getSelect_datanasc() {
        return select_datanasc;
    }

    public void setSelect_datanasc(JTextField select_datanasc) {
        this.select_datanasc = select_datanasc;
    }

    public JTextField getSelect_email1() {
        return select_email1;
    }

    public void setSelect_email1(JTextField select_email1) {
        this.select_email1 = select_email1;
    }

    public JTextField getSelect_nome() {
        return select_nome;
    }

    public void setSelect_nome(JTextField select_nome) {
        this.select_nome = select_nome;
    }

    public JTextArea getSelect_objetivo() {
        return select_objetivo;
    }

    public void setSelect_objetivo(JTextArea select_objetivo) {
        this.select_objetivo = select_objetivo;
    }

    public JPasswordField getSelect_senha() {
        return select_senha;
    }

    public void setSelect_senha(JPasswordField select_senha) {
        this.select_senha = select_senha;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Dados_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Dados_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Dados_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Dados_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Dados_aluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField select_cpf;
    private javax.swing.JTextField select_datanasc;
    private javax.swing.JTextField select_email1;
    private javax.swing.JTextField select_nome;
    private javax.swing.JTextArea select_objetivo;
    private javax.swing.JPasswordField select_senha;
    // End of variables declaration//GEN-END:variables
}
