/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas_view;

import Academia.Cadastro;
import Academia.Personal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author matheus 
 */
public class Tela_cadastro_personal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_cadastro_personal
     */
    public Tela_cadastro_personal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        insertp_email = new javax.swing.JTextField();
        insertp_nome = new javax.swing.JTextField();
        insertp_senha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        insertp_especialidade = new javax.swing.JTextArea();
        insertp_cpf = new javax.swing.JFormattedTextField();
        insertp_datanasc = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel2.setText(":");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 30, 40));

        insertp_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertp_emailActionPerformed(evt);
            }
        });
        getContentPane().add(insertp_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 260, 30));
        getContentPane().add(insertp_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 260, 30));

        insertp_senha.setText("jPasswordField1");
        getContentPane().add(insertp_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 260, 30));

        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 433, 290, 100));

        insertp_especialidade.setColumns(20);
        insertp_especialidade.setRows(5);
        jScrollPane1.setViewportView(insertp_especialidade);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, -1, -1));

        try {
            insertp_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(insertp_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 260, 30));

        try {
            insertp_datanasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(insertp_datanasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro_personal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insertp_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertp_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertp_emailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Personal pers = new Personal();
        pers.setNome(this.getInsertp_nome().getText());
        pers.setCpf(this.getInsertp_cpf().getText());
        pers.setEspecialidade(this.getInsertp_especialidade().getText());
        pers.setEmail(this.getInsertp_email().getText());
        pers.setSenha(this.getInsertp_senha().getText());
        pers.setDataNasc(this.getInsertp_datanasc().getText());
        pers.setSalario(1500);
        pers.setBonus_por_aluno(0);
        pers.setQtd_aluno(0);
        pers.setTipo("personal");
        
        Cadastro cadp = new Cadastro();
        try {
            cadp.inserir(pers);
            JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");
            this.setVisible(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, "Tente novamente!");
            Logger.getLogger(Tela_cadastro_aluno.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public JFormattedTextField getInsertp_cpf() {
        return insertp_cpf;
    }

    public void setInsertp_cpf(JFormattedTextField insertp_cpf) {
        this.insertp_cpf = insertp_cpf;
    }

    public JFormattedTextField getInsertp_datanasc() {
        return insertp_datanasc;
    }

    public void setInsertp_datanasc(JFormattedTextField insertp_datanasc) {
        this.insertp_datanasc = insertp_datanasc;
    }

    public JTextField getInsertp_email() {
        return insertp_email;
    }

    public void setInsertp_email(JTextField insertp_email) {
        this.insertp_email = insertp_email;
    }

    public JTextArea getInsertp_especialidade() {
        return insertp_especialidade;
    }

    public void setInsertp_especialidade(JTextArea insertp_especialidade) {
        this.insertp_especialidade = insertp_especialidade;
    }

    public JTextField getInsertp_nome() {
        return insertp_nome;
    }

    public void setInsertp_nome(JTextField insertp_nome) {
        this.insertp_nome = insertp_nome;
    }

    public JPasswordField getInsertp_senha() {
        return insertp_senha;
    }

    public void setInsertp_senha(JPasswordField insertp_senha) {
        this.insertp_senha = insertp_senha;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_cadastro_personal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField insertp_cpf;
    private javax.swing.JFormattedTextField insertp_datanasc;
    private javax.swing.JTextField insertp_email;
    private javax.swing.JTextArea insertp_especialidade;
    private javax.swing.JTextField insertp_nome;
    private javax.swing.JPasswordField insertp_senha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
