/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas_view;

import Academia.Aluno;
import Academia.Cadastro;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author janiele
 */
public class Tela_cadastro_aluno extends javax.swing.JFrame {

    /**
     * Creates new form Tela_cadastro_aluno
     */
    public Tela_cadastro_aluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insert_email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        insert_objetivo = new javax.swing.JTextArea();
        insert_senha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        insert_nome = new javax.swing.JTextField();
        insert_cpf = new javax.swing.JFormattedTextField();
        insert_datansc = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insert_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_emailActionPerformed(evt);
            }
        });
        getContentPane().add(insert_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 300, 30));

        insert_objetivo.setColumns(20);
        insert_objetivo.setRows(5);
        jScrollPane1.setViewportView(insert_objetivo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        insert_senha.setText("jPasswordField1");
        getContentPane().add(insert_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 290, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 90, 60));

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 260, 100));

        insert_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(insert_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 290, 30));

        try {
            insert_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(insert_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 300, 30));

        try {
            insert_datansc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(insert_datansc, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_cadastro_aluno.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insert_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insert_emailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Aluno alu = new Aluno();
        alu.setNome(this.getInsert_nome().getText());
        alu.setCpf(this.getInsert_cpf().getText());
        alu.setEmail(this.getInsert_email().getText());
        alu.setSenha(new String(this.getInsert_senha().getPassword()));
        alu.setObjetivo(this.getInsert_objetivo().getText());
        alu.setDataNasc(this.getInsert_datansc().getText());
        alu.setMatricula("Mat" + new Random().nextInt(1000000)); // ou algo semelhante
        alu.setStatus("ativo");
        alu.setTipo("aluno");
        Cadastro cad = new Cadastro();
        try {
            cad.inserir(alu);
            JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");
            this.setVisible(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, "Tente novamente!");
            Logger.getLogger(Tela_cadastro_aluno.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void insert_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insert_nomeActionPerformed

    public JFormattedTextField getInsert_cpf() {
        return insert_cpf;
    }

    public void setInsert_cpf(JFormattedTextField insert_cpf) {
        this.insert_cpf = insert_cpf;
    }

    public JFormattedTextField getInsert_datansc() {
        return insert_datansc;
    }

    public void setInsert_datansc(JFormattedTextField insert_datansc) {
        this.insert_datansc = insert_datansc;
    }

    public JTextField getInsert_email() {
        return insert_email;
    }

    public void setInsert_email(JTextField insert_email) {
        this.insert_email = insert_email;
    }

    public JTextArea getInsert_objetivo() {
        return insert_objetivo;
    }

    public void setInsert_objetivo(JTextArea insert_objetivo) {
        this.insert_objetivo = insert_objetivo;
    }

    public JPasswordField getInsert_senha() {
        return insert_senha;
    }

    public void setInsert_senha(JPasswordField insert_senha) {
        this.insert_senha = insert_senha;
    }

    public JTextField getInsert_nome() {
        return insert_nome;
    }

    public void setInsert_nome(JTextField insert_nome) {
        this.insert_nome = insert_nome;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_cadastro_aluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField insert_cpf;
    private javax.swing.JFormattedTextField insert_datansc;
    private javax.swing.JTextField insert_email;
    private javax.swing.JTextField insert_nome;
    private javax.swing.JTextArea insert_objetivo;
    private javax.swing.JPasswordField insert_senha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
