/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas_view;

import Academia.Adm;
import Academia.Cadastro;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author samue
 */
public class Tela_cadastro_adm extends javax.swing.JFrame {

    /**
     * Creates new form Tela_cadastro_adm
     */
    public Tela_cadastro_adm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insertad_setor = new javax.swing.JTextField();
        insertad_email = new javax.swing.JTextField();
        insertad_telefone = new javax.swing.JTextField();
        insertad_cpf = new javax.swing.JTextField();
        insertad_datanasc = new javax.swing.JTextField();
        insertad_nome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        insertad_dsc = new javax.swing.JTextArea();
        insertad_senha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insertad_setor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertad_setorActionPerformed(evt);
            }
        });
        getContentPane().add(insertad_setor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 270, 30));

        insertad_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertad_emailActionPerformed(evt);
            }
        });
        getContentPane().add(insertad_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 270, 30));

        insertad_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertad_telefoneActionPerformed(evt);
            }
        });
        getContentPane().add(insertad_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 260, 30));

        insertad_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertad_cpfActionPerformed(evt);
            }
        });
        getContentPane().add(insertad_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 260, 30));

        insertad_datanasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertad_datanascActionPerformed(evt);
            }
        });
        getContentPane().add(insertad_datanasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 240, 30));

        insertad_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertad_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(insertad_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 270, 30));

        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 503, 280, 110));

        insertad_dsc.setColumns(20);
        insertad_dsc.setRows(5);
        jScrollPane1.setViewportView(insertad_dsc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, -1, -1));

        insertad_senha.setText("jPasswordField1");
        getContentPane().add(insertad_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 270, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel1.setText(":");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 10, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro_adm.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 1053, 691));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insertad_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertad_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertad_telefoneActionPerformed

    private void insertad_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertad_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertad_cpfActionPerformed

    private void insertad_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertad_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertad_emailActionPerformed

    private void insertad_setorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertad_setorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertad_setorActionPerformed

    private void insertad_datanascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertad_datanascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertad_datanascActionPerformed

    private void insertad_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertad_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertad_nomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Adm admt = new Adm();
        admt.setNome(this.getInsertad_nome().getText());
        admt.setCpf(this.getInsertad_cpf().getText());
        admt.setSetor(this.getInsertad_setor().getText());
        admt.setEmail(this.getInsertad_email().getText());
        admt.setSenha(this.getInsertad_senha().getText());
        admt.setDataNasc(this.getInsertad_datanasc().getText());
        admt.setNumero_comercial(this.getInsertad_telefone().getText());
        admt.setDesc(this.getInsertad_dsc().getText());
        admt.setSalario(3000);
        admt.setTipo("adm");
        
        Cadastro cad_adm = new Cadastro();
        
         try {
            cad_adm.inserir(admt);
            JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");
            this.setVisible(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, "Tente novamente!");
            Logger.getLogger(Tela_cadastro_aluno.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setVisible(false);
        
        
                
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public JTextField getInsertad_cpf() {
        return insertad_cpf;
    }

    public void setInsertad_cpf(JTextField insertad_cpf) {
        this.insertad_cpf = insertad_cpf;
    }

    public JTextField getInsertad_datanasc() {
        return insertad_datanasc;
    }

    public void setInsertad_datanasc(JTextField insertad_datanasc) {
        this.insertad_datanasc = insertad_datanasc;
    }

    public JTextArea getInsertad_dsc() {
        return insertad_dsc;
    }

    public void setInsertad_dsc(JTextArea insertad_dsc) {
        this.insertad_dsc = insertad_dsc;
    }

    public JTextField getInsertad_email() {
        return insertad_email;
    }

    public void setInsertad_email(JTextField insertad_email) {
        this.insertad_email = insertad_email;
    }

    public JTextField getInsertad_nome() {
        return insertad_nome;
    }

    public void setInsertad_nome(JTextField insertad_nome) {
        this.insertad_nome = insertad_nome;
    }

    public JPasswordField getInsertad_senha() {
        return insertad_senha;
    }

    public void setInsertad_senha(JPasswordField insertad_senha) {
        this.insertad_senha = insertad_senha;
    }

    public JTextField getInsertad_setor() {
        return insertad_setor;
    }

    public void setInsertad_setor(JTextField insertad_setor) {
        this.insertad_setor = insertad_setor;
    }

    public JTextField getInsertad_telefone() {
        return insertad_telefone;
    }

    public void setInsertad_telefone(JTextField insertad_telefone) {
        this.insertad_telefone = insertad_telefone;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_cadastro_adm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField insertad_cpf;
    private javax.swing.JTextField insertad_datanasc;
    private javax.swing.JTextArea insertad_dsc;
    private javax.swing.JTextField insertad_email;
    private javax.swing.JTextField insertad_nome;
    private javax.swing.JPasswordField insertad_senha;
    private javax.swing.JTextField insertad_setor;
    private javax.swing.JTextField insertad_telefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
