/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas_view;

import Academia.Aluno;
import Academia.Metodos;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samuel e heitor
 */
public class Tela_escolherPersonal_plus extends javax.swing.JFrame {
    public void preencherTabela() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) Listar_personal.getModel();
        modelo.setRowCount(0); // limpa tabela

        Metodos mt = new Metodos();
        List<Object[]> dados = mt.Dados_personal();
        for (Object[] linha : dados) {
            modelo.addRow(linha);
        }
    }
    /**
     * Creates new form Tela_escolherPersonal_plus
     */
    public Tela_escolherPersonal_plus() {
        initComponents();
        try {
            preencherTabela();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Listar_personal = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 300, 100));

        Listar_personal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Especialidade"
            }
        ));
        jScrollPane1.setViewportView(Listar_personal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_escolherPersonal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1045, 659));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int linha_selecionada = Listar_personal.getSelectedRow();
        if (linha_selecionada != -1) { // verifica se alguma linha foi selecionada
            String nome = Listar_personal.getValueAt(linha_selecionada, 0).toString(); // coluna 0
            String especialidade = Listar_personal.getValueAt(linha_selecionada, 1).toString(); // coluna 1

            try {
                Aluno aluno = (Aluno) Sessao_usuario.getUsuarioLogado();
                Metodos mts = new Metodos();
                mts.obterIdPersonal(nome);
                mts.contratarPlano(mts.obterIdAluno(mts.retornoID(aluno.getEmail())), mts.obterIdPersonal(nome), 90.0, 12, "Premium Plus", 1);
                JOptionPane.showMessageDialog(this, "Plano contratado com sucesso");
                this.dispose();
                Tela_planos  tl = new Tela_planos();
                tl.setVisible(true);
                
            } catch (SQLException ex) {
                Logger.getLogger(Tela_escolherPersonal.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "erro!");
            } catch (Exception ex) {
                Logger.getLogger(Tela_escolherPersonal.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "erro!");
            }
        } else {
           JOptionPane.showMessageDialog(this, "Nenhuma linha selecionada!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_escolherPersonal_plus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_escolherPersonal_plus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_escolherPersonal_plus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_escolherPersonal_plus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_escolherPersonal_plus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Listar_personal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
